### PR TITLE
statement.split(";") cannot be used with strings which contains symbo…

### PR DESCRIPTION
**Pull request by urvanov-ru**
…l ";" like "vasya;petya". I think, it would be better to check for the end of line after ";" symbol. At least we would have an opportunity to use semicolons in text.

Example for test:
https://github.com/urvanov-ru/cassandra-maven-plugin-semicolon-test

### CODE REVIEW

**Comment by urvanov-ru** [comment]
@olamy ?

**Comment by giejay** [comment]
Looks good, but unfortunately I do not have the access rights to merge it

**Comment by djarnis73** [comment]
This is not a fix in my opinion, it will quickly break with a cryptic error message (like today), I have a version that uses the cql lexer, so it should handle any wellformed cql. But I did not have time to polish it into a PR.

The splitter code looks like this:

```java
protected static String[] splitStatementsUsingCqlLexer(String statements) {
    ANTLRStringStream stream = new ANTLRStringStream(statements);
    CqlLexer lexer = new CqlLexer(stream);
    ArrayList<String> statementList = new ArrayList<String>();
    StringBuffer currentStatement = new StringBuffer();
    boolean inComment;
    // Not the prettiest code i ever wrote, but it gets the job done.
    for (Token token = lexer.nextToken(); token.getType() != Token.EOF; token = lexer.nextToken()) {
        if (token.getText().equals(";")) {
            // when we meet a ; terminate current statement and prepare the next
            currentStatement.append(";");
            statementList.add(currentStatement.toString());
            currentStatement = new StringBuffer();
        } else if (token.getType() == CqlLexer.STRING_LITERAL) {
            // If we meet a string we should quote it and escape any enclosed ' as ''
            currentStatement.append("'");
            // TODO: There must be a cassandra util method somewhere that escapes a string for sql
            currentStatement.append(token.getText().replaceAll("'", "''"));
            currentStatement.append("'");
        } else {
            currentStatement.append(token.getText());
        }
    }
    if (currentStatement.length() > 0 && currentStatement.toString().trim().length() > 0) {
        statementList.add(currentStatement.toString());
    }
    return statementList.toArray(new String[statementList.size()]);
}
```

**Comment by urvanov-ru** [comment]
Thanks. I will try to update my pull request with your code.

**Comment by djarnis73** [comment]
I have pushed my changes to my clone, you can see full commit here: https://github.com/djarnis73/cassandra-maven-plugin/commit/0ed68b2ebbc196309842ca512ffd9d89e1dcf628 i can make a PR for it if it looks good to you.

**Comment by urvanov-ru** [comment]
@djarnis73 Your code much better but it is not finished yet. It does not work with my cql-code from my job for which I trying to adapt the plugin. And it still has problems with comments. I will try to fix it. I will make a pull request when I finish.

**Comment by urvanov-ru** [comment]
Fixed.

**Comment by urvanov-ru** [comment]
@stephenc @seblm @ajs6f @giejay @djarnis73 @Willem1987 @dmitrymurashenkov @olamy

**Comment by urvanov-ru** [comment]
@stephenc @seblm @ajs6f @giejay @djarnis73 @Willem1987 @dmitrymurashenkov @olamy         
Are there any guys with write permissions?

**Comment by ajs6f** [comment]
I don't know why you think I can merge your work. I have no role in this project and have never contributed to it.

**Comment by urvanov-ru** [comment]
I think It is better to fork this repo and produce my own version of this plugin. I have really no idea whom and how should I push to force him to merge this branch.

**Pull request merged**
